################################################################
## GENERAL PARAMETERS
##
description: ""
author: "Claire Rioualen and Jacques van Helden"
title: "NarL demo case"
dataset: ""
qsub: "-V -m a -d ." 
genome:
  organism: "Escherichia coli K12 MG1655"
  version: "Ecoli_K12"
  size: "4639221"
  fasta_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.toplevel.fa
  fasta_url_base: ftp://ftp.ensemblgenomes.org/pub/release-43/bacteria//fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/dna
  gff3_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3
  gff3_url_base: ftp://ftp.ensemblgenomes.org/pub/release-43/bacteria//gff3/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655
  gtf_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.43.gtf
  gtf_url_base: ftp://ftp.ensemblgenomes.org/pub/release-43/bacteria//gtf/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655
    
dir:
  genome: "genome"
  regulondb: "RegulonDB"

metadata:
  configfile: ""                         
  TF: "NarL"
