################################################################
## GENERAL PARAMETERS
##
  description: ""
  author: "Claire Rioualen and Jacques van Helden"
  title: "NarL demo case"
  dataset: ""
  qsub: "-V -m a -d ." 
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"
    size: "4639221"
    fasta_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.chromosome.Chromosome.fa
    gff3_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3
    gtf_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.gtf
    
  dir:
    genome: "genome"
    regulondb: "RegulonDB"

  metadata:
    configfile: ""                         
    TF: "NarL"